const images = {
    logo: require('~/assets/images/logo.png'),
    defaultAvatar: require('~/assets/images/default-avatar.png'),
    bannerImg: require('~/assets/images/banner-img.webp'),
    netflixN: require('~/assets/images/netflix_n.png'),

    // Carousel Images
    carouselImg1: require('~/assets/images/carouselImg/carousel-img-1.webp'),
    carouselImg2: require('~/assets/images/carouselImg/carousel-img-2.jpg'),
    carouselImg3: require('~/assets/images/carouselImg/carousel-img-3.webp'),
    carouselImg4: require('~/assets/images/carouselImg/carousel-img-4.webp'),
    carouselImg5: require('~/assets/images/carouselImg/carousel-img-5.jpg'),
    carouselImg6: require('~/assets/images/carouselImg/carousel-img-6.webp'),
    carouselImg7: require('~/assets/images/carouselImg/carousel-img-7.webp'),
    carouselImg8: require('~/assets/images/carouselImg/carousel-img-8.webp'),
    carouselImg9: require('~/assets/images/carouselImg/carousel-img-9.webp'),
    carouselImg10: require('~/assets/images/carouselImg/carousel-img-10.webp'),
    carouselImg11: require('~/assets/images/carouselImg/carousel-img-11.webp'),
    carouselImg12: require('~/assets/images/carouselImg/carousel-img-12.webp'),
    carouselImg13: require('~/assets/images/carouselImg/carousel-img-13.webp'),
    carouselImg14: require('~/assets/images/carouselImg/carousel-img-14.webp'),
    carouselImg15: require('~/assets/images/carouselImg/carousel-img-15.webp'),
    carouselImg16: require('~/assets/images/carouselImg/carousel-img-16.webp'),
    carouselImg17: require('~/assets/images/carouselImg/carousel-img-17.webp'),
    carouselImg18: require('~/assets/images/carouselImg/carousel-img-18.webp'),
    carouselImg19: require('~/assets/images/carouselImg/carousel-img-19.webp'),
    carouselImg20: require('~/assets/images/carouselImg/carousel-img-20.jpg'),
    carouselImg21: require('~/assets/images/carouselImg/carousel-img-21.jpg'),
    carouselImg22: require('~/assets/images/carouselImg/carousel-img-22.jpg'),
    carouselImg23: require('~/assets/images/carouselImg/carousel-img-23.webp'),
    carouselImg24: require('~/assets/images/carouselImg/carousel-img-24.webp'),
    carouselImg25: require('~/assets/images/carouselImg/carousel-img-25.webp'),
    carouselImg26: require('~/assets/images/carouselImg/carousel-img-26.webp'),
    carouselImg27: require('~/assets/images/carouselImg/carousel-img-27.jpg'),
    carouselImg28: require('~/assets/images/carouselImg/carousel-img-28.jpg'),
    carouselImg29: require('~/assets/images/carouselImg/carousel-img-29.webp'),
    carouselImg30: require('~/assets/images/carouselImg/carousel-img-30.webp'),
    carouselImg31: require('~/assets/images/carouselImg/carousel-img-31.webp'),
    carouselImg32: require('~/assets/images/carouselImg/carousel-img-32.webp'),
    carouselImg33: require('~/assets/images/carouselImg/carousel-img-33.webp'),
    carouselImg34: require('~/assets/images/carouselImg/carousel-img-34.webp'),
    carouselImg35: require('~/assets/images/carouselImg/carousel-img-35.jpg'),
    carouselImg36: require('~/assets/images/carouselImg/carousel-img-36.webp'),
    carouselImg37: require('~/assets/images/carouselImg/carousel-img-37.jpg'),

    // More like this image
    moreLikeThisImg1: require('~/assets/images/moreLikeThisImg/more-like-this-img-1.webp'),
    moreLikeThisImg2: require('~/assets/images/moreLikeThisImg/more-like-this-img-2.webp'),
    moreLikeThisImg3: require('~/assets/images/moreLikeThisImg/more-like-this-img-3.webp'),
    moreLikeThisImg4: require('~/assets/images/moreLikeThisImg/more-like-this-img-4.webp'),
    moreLikeThisImg5: require('~/assets/images/moreLikeThisImg/more-like-this-img-5.webp'),
    moreLikeThisImg6: require('~/assets/images/moreLikeThisImg/more-like-this-img-6.webp'),
};

export default images;
