import { MovieInformation } from '~/models';
import images from '~/assets/images';

export const bannerMovieInfo: MovieInformation = {
    id: 1,
    name: 'One Piece',
    bgImage: images.bannerImg,
    description: `A new adventure begins for Luffy and his crew when mysterious pop superstar Uta unveils her identity — and launches a misguided plan for world peace.`,
    cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
    genres: ['Action Anime', 'Anime Series', 'Japanese'],
    release: '2024',
    episodes: 10,
    maturity: ['nudity', 'suggestive content', 'violence'],
};

export const carouselList: Array<MovieInformation> = [
    {
        id: 2,
        name: 'Sailor Moon',
        bgImage: images.carouselImg1,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 8,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 3,
        name: 'Sailor Moon',
        bgImage: images.carouselImg2,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 10,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 4,
        name: 'Sailor Moon',
        bgImage: images.carouselImg3,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 9,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 5,
        name: 'Sailor Moon',
        bgImage: images.carouselImg4,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 15,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 6,
        name: 'Sailor Moon',
        bgImage: images.carouselImg5,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 10,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 7,
        name: 'Sailor Moon',
        bgImage: images.carouselImg6,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 15,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 8,
        name: 'Sailor Moon',
        bgImage: images.carouselImg7,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 10,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 9,
        name: 'Sailor Moon',
        bgImage: images.carouselImg8,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 12,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 10,
        name: 'Sailor Moon',
        bgImage: images.carouselImg9,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 11,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 11,
        name: 'Sailor Moon',
        bgImage: images.carouselImg10,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 12,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 12,
        name: 'Sailor Moon',
        bgImage: images.carouselImg11,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 8,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 13,
        name: 'Sailor Moon',
        bgImage: images.carouselImg12,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 9,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 14,
        name: 'Sailor Moon',
        bgImage: images.carouselImg13,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 10,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 15,
        name: 'Sailor Moon',
        bgImage: images.carouselImg14,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 16,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 16,
        name: 'Sailor Moon',
        bgImage: images.carouselImg15,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 12,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 17,
        name: 'Sailor Moon',
        bgImage: images.carouselImg16,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 10,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 18,
        name: 'Sailor Moon',
        bgImage: images.carouselImg17,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 14,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 19,
        name: 'Sailor Moon',
        bgImage: images.carouselImg18,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 12,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 20,
        name: 'Sailor Moon',
        bgImage: images.carouselImg19,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 12,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 21,
        name: 'Sailor Moon',
        bgImage: images.carouselImg20,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 14,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 22,
        name: 'Sailor Moon',
        bgImage: images.carouselImg21,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 8,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 23,
        name: 'Sailor Moon',
        bgImage: images.carouselImg22,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 8,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 24,
        name: 'Sailor Moon',
        bgImage: images.carouselImg23,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 9,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 25,
        name: 'Sailor Moon',
        bgImage: images.carouselImg24,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 9,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 26,
        name: 'Sailor Moon',
        bgImage: images.carouselImg25,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 10,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 27,
        name: 'Sailor Moon',
        bgImage: images.carouselImg26,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 10,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 28,
        name: 'Sailor Moon',
        bgImage: images.carouselImg27,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 12,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 29,
        name: 'Sailor Moon',
        bgImage: images.carouselImg28,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 16,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 30,
        name: 'Sailor Moon',
        bgImage: images.carouselImg29,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 15,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 31,
        name: 'Sailor Moon',
        bgImage: images.carouselImg30,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 8,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 32,
        name: 'Sailor Moon',
        bgImage: images.carouselImg31,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 14,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 33,
        name: 'Sailor Moon',
        bgImage: images.carouselImg32,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 10,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 34,
        name: 'Sailor Moon',
        bgImage: images.carouselImg33,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 9,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 35,
        name: 'Sailor Moon',
        bgImage: images.carouselImg34,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 8,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 36,
        name: 'Sailor Moon',
        bgImage: images.carouselImg35,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 8,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 37,
        name: 'Sailor Moon',
        bgImage: images.carouselImg36,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 8,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 38,
        name: 'Sailor Moon',
        bgImage: images.carouselImg37,
        description: `One by one, Sailor Moon's friends and loved ones are targeted by a formidable new enemy who threatens to destroy everything and rule over the cosmos`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 20,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
];

export const moreLikeList: Array<MovieInformation> = [
    {
        id: 39,
        name: 'One Piece',
        bgImage: images.moreLikeThisImg1,
        description: `A new adventure begins for Luffy and his crew when mysterious pop superstar Uta unveils her identity — and launches a misguided plan for world peace.`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 20,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 40,
        name: 'One Piece',
        bgImage: images.moreLikeThisImg2,
        description: `A new adventure begins for Luffy and his crew when mysterious pop superstar Uta unveils her identity — and launches a misguided plan for world peace.`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 20,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 41,
        name: 'One Piece',
        bgImage: images.moreLikeThisImg3,
        description: `A new adventure begins for Luffy and his crew when mysterious pop superstar Uta unveils her identity — and launches a misguided plan for world peace.`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 20,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 42,
        name: 'One Piece',
        bgImage: images.moreLikeThisImg4,
        description: `A new adventure begins for Luffy and his crew when mysterious pop superstar Uta unveils her identity — and launches a misguided plan for world peace.`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 20,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 43,
        name: 'One Piece',
        bgImage: images.moreLikeThisImg5,
        description: `A new adventure begins for Luffy and his crew when mysterious pop superstar Uta unveils her identity — and launches a misguided plan for world peace.`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 20,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 44,
        name: 'One Piece',
        bgImage: images.moreLikeThisImg6,
        description: `A new adventure begins for Luffy and his crew when mysterious pop superstar Uta unveils her identity — and launches a misguided plan for world peace.`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 20,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
];

export const rankCarouselList: Array<MovieInformation> = [
    {
        id: 45,
        name: 'One Piece',
        bgImage: images.rankCarouselImg1,
        description: `A new adventure begins for Luffy and his crew when mysterious pop superstar Uta unveils her identity — and launches a misguided plan for world peace.`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 20,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 46,
        name: 'One Piece',
        bgImage: images.rankCarouselImg2,
        description: `A new adventure begins for Luffy and his crew when mysterious pop superstar Uta unveils her identity — and launches a misguided plan for world peace.`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 20,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 47,
        name: 'One Piece',
        bgImage: images.rankCarouselImg3,
        description: `A new adventure begins for Luffy and his crew when mysterious pop superstar Uta unveils her identity — and launches a misguided plan for world peace.`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 20,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 48,
        name: 'One Piece',
        bgImage: images.rankCarouselImg4,
        description: `A new adventure begins for Luffy and his crew when mysterious pop superstar Uta unveils her identity — and launches a misguided plan for world peace.`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 20,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 49,
        name: 'One Piece',
        bgImage: images.rankCarouselImg5,
        description: `A new adventure begins for Luffy and his crew when mysterious pop superstar Uta unveils her identity — and launches a misguided plan for world peace.`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 20,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 50,
        name: 'One Piece',
        bgImage: images.rankCarouselImg6,
        description: `A new adventure begins for Luffy and his crew when mysterious pop superstar Uta unveils her identity — and launches a misguided plan for world peace.`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 20,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 51,
        name: 'One Piece',
        bgImage: images.rankCarouselImg7,
        description: `A new adventure begins for Luffy and his crew when mysterious pop superstar Uta unveils her identity — and launches a misguided plan for world peace.`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 20,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 52,
        name: 'One Piece',
        bgImage: images.rankCarouselImg8,
        description: `A new adventure begins for Luffy and his crew when mysterious pop superstar Uta unveils her identity — and launches a misguided plan for world peace.`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 20,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 53,
        name: 'One Piece',
        bgImage: images.rankCarouselImg9,
        description: `A new adventure begins for Luffy and his crew when mysterious pop superstar Uta unveils her identity — and launches a misguided plan for world peace.`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 20,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
    {
        id: 54,
        name: 'One Piece',
        bgImage: images.rankCarouselImg10,
        description: `A new adventure begins for Luffy and his crew when mysterious pop superstar Uta unveils her identity — and launches a misguided plan for world peace.`,
        cast: 'Kotono Mitsuishi, Kenji Nojima, Misato Fukuen',
        genres: ['Action Anime', 'Anime Series', 'Japanese'],
        release: '2024',
        episodes: 20,
        maturity: ['nudity', 'suggestive content', 'violence'],
    },
];
